### ISSUE TITLE
ComputeSharp GPU Image Processing

### ISSUE THREAD

**Issue by MosGeo** [swharden/Csharp-Image-Analysis#1]
Great initiative!

You might want to consider ComputeSharp as it allows processing on the GPU which might be needed for running intensive scientific processes on 2D images. I am thinking of things such as Lattice Boltzmann simulations.

[ComputeSharp GitHub Website](https://github.com/Sergio0694/ComputeSharp#working-with-images)

Cheers!

**Comment by swharden** [comment]
Thanks for the tip! This is a great resource to have on hand...

> I am thinking of things such as Lattice Boltzmann simulations

lol I was thinking more like how to convert pictures between RGB and Grayscale 😜

In reality what I'll work on first are some basics: working with multi-channel images, image stack TIFs, and simple routines to perform convolution. It would be great to be able to do these things with some simple copy/paste-able code without having to undertake a huge library or sticky license. Also converting 2D images to/from frequency domain using FFT would be great https://github.com/swharden/FftSharp/issues/29
